coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment: false

ignore:
  - "moonglass-core/src/crypto/kzg.rs"
  - "moonglass-core/src/crypto/kzg/**"
  - "tests/**"
